### ISSUE TITLE
Intermittent problem with metadig-scheduler

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#194]
The k8s pod 'metadig-scheduler' has an intermittent problem where arcticdata.io task causes this java exception:

```
ERROR [DefaultQuartzScheduler_Worker-2] (RequestReportJob.java:108) - Error creating rest client: -1
ERROR [DefaultQuartzScheduler_Worker-1] (RequestReportJob.java:108) - Error creating rest client: null
[DefaultQuartzScheduler_Worker-1] INFO org.quartz.core.JobRunShell - Job metadig.quality-knb threw a JobExecutionException:
[DefaultQuartzScheduler_Worker-2] INFO org.quartz.core.JobRunShell - Job metadig.quality-arctic threw a JobExecutionException:
org.quartz.JobExecutionException: Unable to schedule job [See nested exception: java.util.NoSuchElementException]
	at edu.ucsb.nceas.mdqengine.scheduler.RequestReportJob.execute(RequestReportJob.java:109)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:862)
	at org.apache.commons.configuration.tree.DefaultConfigurationNode$SubNodes.visit(DefaultConfigurationNode.java:667)
	at org.apache.commons.configuration.tree.DefaultConfigurationNode.visit(DefaultConfigurationNode.java:417)
	at org.apache.commons.configuration.HierarchicalConfiguration.nodeDefined(HierarchicalConfiguration.java:969)
	at org.apache.commons.configuration.HierarchicalConfiguration.removeNode(HierarchicalConfiguration.java:1000)
	at org.apache.commons.configuration.HierarchicalConfiguration.clearNode(HierarchicalConfiguration.java:1031)
	at org.apache.commons.configuration.HierarchicalConfiguration.clearProperty(HierarchicalConfiguration.java:795)
	at org.apache.commons.configuration.CompositeConfiguration.clearPropertyDirect(CompositeConfiguration.java:269)
	at org.apache.commons.configuration.AbstractConfiguration.clearProperty(AbstractConfiguration.java:501)
	at org.apache.commons.configuration.AbstractConfiguration.setProperty(AbstractConfiguration.java:481)
	at org.dataone.client.rest.HttpMultipartRestClient.setDefaultTimeout(HttpMultipartRestClient.java:588)
	at org.dataone.client.rest.HttpMultipartRestClient.<init>(HttpMultipartRestClient.java:222)
	at org.dataone.client.rest.HttpMultipartRestClient.<init>(HttpMultipartRestClient.java:199)
	at org.dataone.client.rest.DefaultHttpMultipartRestClient.<init>(DefaultHttpMultipartRestClient.java:40)
	at edu.ucsb.nceas.mdqengine.scheduler.RequestReportJob.execute(RequestReportJob.java:106)
	... 2 more
org.quartz.JobExecutionException: Unable to schedule job [See nested exception: java.lang.ArrayIndexOutOfBoundsException: -1]
	at edu.ucsb.nceas.mdqengine.scheduler.RequestReportJob.execute(RequestReportJob.java:109)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.fastRemove(ArrayList.java:550)
	at java.util.ArrayList.remove(ArrayList.java:533)
	at org.apache.commons.configuration.tree.DefaultConfigurationNode$SubNodes.removeNode(DefaultConfigurationNode.java:544)
	at org.apache.commons.configuration.tree.DefaultConfigurationNode.removeChild(DefaultConfigurationNode.java:250)
	at org.apache.commons.configuration.HierarchicalConfiguration.removeNode(HierarchicalConfiguration.java:999)
	at org.apache.commons.configuration.HierarchicalConfiguration.clearNode(HierarchicalConfiguration.java:1031)
	at org.apache.commons.configuration.HierarchicalConfiguration.clearProperty(HierarchicalConfiguration.java:795)
	at org.apache.commons.configuration.CompositeConfiguration.clearPropertyDirect(CompositeConfiguration.java:269)
	at org.apache.commons.configuration.AbstractConfiguration.clearProperty(AbstractConfiguration.java:501)
	at org.apache.commons.configuration.AbstractConfiguration.setProperty(AbstractConfiguration.java:481)
	at org.dataone.client.rest.HttpMultipartRestClient.setDefaultTimeout(HttpMultipartRestClient.java:588)
	at org.dataone.client.rest.HttpMultipartRestClient.<init>(HttpMultipartRestClient.java:222)
	at org.dataone.client.rest.HttpMultipartRestClient.<init>(HttpMultipartRestClient.java:199)
	at org.dataone.client.rest.DefaultHttpMultipartRestClient.<init>(DefaultHttpMultipartRestClient.java:40)
	at edu.ucsb.nceas.mdqengine.scheduler.RequestReportJob.execute(RequestReportJob.java:106)
	... 2 more
 INFO [DefaultQuartzScheduler_Worker-3] (CertificateManager.java:1144) - selectSession: using the default certificate location
 INFO [DefaultQuartzScheduler_Worker-3] (CertificateManager.java:1134) - Did not find a certificate for the subject specified: null
```

**Comment by gothub** [comment]
When a `metadig-scheduler` task encounters an error (i.e. connection timeout to harvested node), have the task throw the proper error so that the task will be rescheduled. Fix in commit aa9c67cf7c8827dd562eb40e55da8db0913cc95e
