### ISSUE TITLE
Add CERP MN to harvest/assessment

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#318]
To add an MN to the assessment harvest:
- add an entry to the metadig-scheduler task file ./helm/metadig-scheduler/config/taskList.csv: 
```
quality,quality-cerp,15 0/1 * * * ?,"^eml.*|^http.*eml.*;FAIR-suite-0.3.1;urn:node:CERP_SFWMD;2010-10-07T00:00:00.00Z;1;1000;"
```
- add entries to the metadig-controller properties file ./helm/metadig-controller/config/metadig.properties:
```
CERP_SFWMD.subjectId = CN=cerp-sfwmd-admins,DC=dataone,DC=org
CERP_SFWMD.serviceUrl = https://cerp-sfwmd.dataone.org/metacat/d1/mn
```

- Restart metadig-controller
   - see operations-manual.md
- Restart metadig-scheduler
   - see operations-manual.md
- inspect the log files of metadig-controller and metadig-scheduler to ensure the the harvest and assessments are running
- inspect a quality report
  - for example: https://cerp-sfwmd.dataone.org/quality/dmarley.1124.11

**Comment by mbjones** [comment]
@taojing2002 when you have CERP up and running I think this metadig config will be needed too.

**Comment by jeanetteclark** [comment]
@mbjones is this still needed?

**Comment by mbjones** [comment]
Well, yes in that we do need for each of the hosted repos to be harvested by DataONE and be sure we are running the FAIR metadata checks on them, and then to configure their MetacatUI installs so that they will properly display all of the aggregated quality and metrics reports (which by default are not shown for non-HR repos). I don't know if Jing did this for CERP and other hosted repos yet. Lauren enabled it for some IIRC.

**Comment by jeanetteclark** [comment]
seems like we need to update a few nodes. to add to metadig.properties:

```
OPC.subjectId = urn:node:OPC
OPC.serviceUrl = https://opc.dataone.org/metacat/d1/mn
CERP_SFWMD.subjectId = urn:node:CERP_SFWMD
CREP_SFWMD.serviceUrl = https://cerp-sfwmd.dataone.org/metacat/d1/mn
SCTLD.subjectId = urn:node:SCTLD
SCTLD.serviceUrl = https://sctld.dataone.org/metacat/d1/mn
DRP.subjectId = urn:node:DRP
DRP.serviceUrl = https://drp.dataone.org/metacat/d1/mn
```

to add to taskList.csv

```
quality,quality-cerp,15 0/1 * * * ?,"^eml.*|^http.*eml.*;FAIR-suite-0.3.1;urn:node:CERP_SFWMD;2010-10-07T00:00:00.00Z;1;1000;"
quality,quality-opc,15 0/1 * * * ?,"^eml.*|^http.*eml.*;FAIR-suite-0.3.1;urn:node:OPC;2010-10-07T00:00:00.00Z;1;1000;"
quality,quality-sctld,15 0/1 * * * ?,"^eml.*|^http.*eml.*;FAIR-suite-0.3.1;urn:node:SCTLD;2010-10-07T00:00:00.00Z;1;1000;"
quality,quality-drp,15 0/1 * * * ?,"^eml.*|^http.*eml.*;FAIR-suite-0.3.1;urn:node:DRP;2010-10-07T00:00:00.00Z;1;1000;"
```

**Comment by jeanetteclark** [comment]
CERP_SFWMD and DRP both return errors like this:

```
20230712-18:18:15: [INFO]: Job metadig.quality-cerp_sfwmd threw a JobExecutionException:  [org.quartz.core.JobRunShell:218]
org.quartz.JobExecutionException: Unable to get pids to process [See nested exception: org.dataone.service.exceptions.ServiceFailure: 403: Forbidden: parser for deserializing HTML not written yet.  Providing message body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.Reason: Cannot perform Post-Handshake Authentication.<br /></p>
</body></html>
]
	at edu.ucsb.nceas.mdqengine.scheduler.RequestReportJob.execute(RequestReportJob.java:339)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.dataone.service.exceptions.ServiceFailure: 403: Forbidden: parser for deserializing HTML not written yet.  Providing message body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.Reason: Cannot perform Post-Handshake Authentication.<br /></p>
</body></html>

```

@taojing2002 is this a cert issue?

**Comment by jeanetteclark** [comment]
this was done, Jing updated what he needed to, and now all the hosted repos have their quality engine/metrics running
