### ISSUE TITLE
fix solr indexing errors with 2.4.1-SNAPSHOT on dev

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-engine#359]
seems the solr index isn't happy on the dev cluster. here is the error (same for all new documents I've seen so far):

```
20230622-21:39:04: [ERROR]: Unable to index quality report.. [edu.ucsb.nceas.mdqengine.Worker:377]
edu.ucsb.nceas.mdqengine.exception.MetadigIndexException: Error during indexing
	at edu.ucsb.nceas.mdqengine.Worker.indexReport(Worker.java:653)
	at edu.ucsb.nceas.mdqengine.Worker$1.handleDelivery(Worker.java:327)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [metadig-index-processor-context.xml]; nested exception is java.io.FileNotFoundException: class path resource [metadig-index-processor-context.xml] cannot be opened because it does not exist
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:341)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:530)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:444)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at edu.ucsb.nceas.mdqengine.solr.IndexApplicationController.getContext(IndexApplicationController.java:83)
	at edu.ucsb.nceas.mdqengine.solr.IndexApplicationController.initialize(IndexApplicationController.java:65)
	at edu.ucsb.nceas.mdqengine.Worker.indexReport(Worker.java:641)
	... 6 more
Caused by: java.io.FileNotFoundException: class path resource [metadig-index-processor-context.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:157)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:328)
	... 21 more

```

**Comment by jeanetteclark** [comment]
Fixed in https://github.com/NCEAS/metadig-engine/commit/a72f998f22fe7c372b14f0aee3786f6b4b56fdd8
